### ISSUE TITLE
The 'ImageResource' class does not implement the 'create_bitmap' method of the 'IImageResource' interface.

### ISSUE THREAD

**Issue by davidok8** [enthought/pyface#102]
- Create the following file 'test.py'

```
import traits.has_traits
traits.has_traits.CHECK_INTERFACES = 2
from traitsui.api import TabularEditor

print "hello"
```

- Run ```ETS_TOOLKIT="qt4" python test.py```.

Here is the traceback:
```
Traceback (most recent call last):
  File "test_pyface.py", line 3, in <module>
    from traitsui.api import TabularEditor
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/api.py", line 35, in <module>
    from .editors.api import (ArrayEditor, BooleanEditor, ButtonEditor,
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/editors/__init__.py", line 22, in <module>
    from .api import (toolkit, ArrayEditor, BooleanEditor, ButtonEditor,
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/editors/api.py", line 29, in <module>
    from .list_str_editor import ListStrEditor
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/editors/list_str_editor.py", line 33, in <module>
    from pyface.image_resource import ImageResource
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyface/image_resource.py", line 19, in <module>
    ImageResource = toolkit_object('image_resource:ImageResource')
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyface/toolkit.py", line 97, in toolkit_object
    __import__(be_mname)
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyface/ui/qt4/image_resource.py", line 29, in <module>
    class ImageResource(MImageResource, HasTraits):
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/has_traits.py", line 3802, in wrapped_class
    check_implements(klass, protocols, CHECK_INTERFACES)
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/interface_checker.py", line 194, in check_implements
    return checker.check_implements( cls, interfaces, error_mode )
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/interface_checker.py", line 90, in check_implements
    error_mode ):
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/interface_checker.py", line 111, in _check_has_traits_class
    self._check_methods( cls, interface, error_mode ))
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/interface_checker.py", line 128, in _check_methods
    self._class_name( interface ) ), error_mode )
  File "/Users/David/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/interface_checker.py", line 178, in _handle_error
    raise InterfaceError( msg )
traits.interface_checker.InterfaceError: The 'ImageResource' class does not implement the 'create_bitmap' method of the 'IImageResource' interface.
```

**Comment by corranwebster** [comment]
This is an issue with the interface checker.  It doesn't handle explicit method assignment to methods from mixins:

    
    import traits.has_traits
    traits.has_traits.CHECK_INTERFACES = 2
    
    from traits.api import Interface, HasTraits, provides
    
    
    class ITest(Interface):
    
        def foo(self):
            pass
    
    class MTest(HasTraits):
    
        def bar(self):
            pass
    
    @provides(ITest)
    class Test(HasTraits):
    
        foo = MTest.bar
    
    
    t = Test()
    t.foo()

**Comment by corranwebster** [comment]
Closing in favour of https://github.com/enthought/traits/issues/257
