### ISSUE TITLE
Trait named 'active_task' not found on <pyface.ui.qt4.application_window.ApplicationWindow object at 0x7fca684fdd00>.

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#1025]
The following traceback shows up in the test suite, both locally and [in CI](https://github.com/enthought/pyface/pull/1023/checks?check_run_id=3626954377). It doesn't cause an actual test failure, but still seems indicative of a possible bug.

```python
test_lifecycle (pyface.tasks.tests.test_tasks_application.TestApplication) ... Exception occurred in traits notification handler for event object: TraitChangeEvent(object=<pyface.ui.qt4.application_window.ApplicationWindow object at 0x7f45a10c48e0>, name='activated', old=<undefined>, new=<pyface.ui.qt4.application_window.ApplicationWindow object at 0x7f45a10c48e0>)
Traceback (most recent call last):
  File "/home/runner/work/pyface/pyface/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/traits/observation/_trait_event_notifier.py", line 122, in __call__
    self.dispatcher(handler, event)
  File "/home/runner/work/pyface/pyface/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/traits/observation/observe.py", line 26, in dispatch_same
    handler(event)
  File "/home/runner/work/pyface/pyface/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/pyface/gui_application.py", line 289, in _on_activate_window
    self.active_window = window
  File "/home/runner/work/pyface/pyface/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/traits/observation/_observer_change_notifier.py", line 152, in __call__
    dispatcher=self.dispatcher,
  File "/home/runner/work/pyface/pyface/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/traits/observation/_has_traits_helpers.py", line 114, in observer_change_handler
    remove=False,
  File "/home/runner/work/pyface/pyface/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/traits/observation/_observe.py", line 54, in add_or_remove_notifiers
    callable_()
  File "/home/runner/work/pyface/pyface/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/traits/observation/_observe.py", line 94, in __call__
    step()
  File "/home/runner/work/pyface/pyface/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/traits/observation/_observe.py", line 163, in _add_or_remove_notifiers
    for observable in self.graph.node.iter_observables(self.object):
  File "/home/runner/work/pyface/pyface/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/traits/observation/_named_trait_observer.py", line 88, in iter_observables
    "Trait named {!r} not found on {!r}.".format(self.name, object)
ValueError: Trait named 'active_task' not found on <pyface.ui.qt4.application_window.ApplicationWindow object at 0x7f45a10c48e0>.
ok
```

**Comment by corranwebster** [comment]
That's a bug in the test - the test is using an `ApplicationWindow` rather than a `TaskWindow` (which is a subclass of `ApplicationWindow`), which is why the `active_task` isn't found.  Most likely a copy-paste error from tests for the `GUIApplication` superclass.

I _think_ the fix is just to use a `TaskWindow` in the test.

**Comment by mdickinson** [comment]
Whoops; this is a duplicate of #906.

**Comment by corranwebster** [comment]
Closing because it is a duplicate.
