### ISSUE TITLE
Bug report: pyqt6 test failure

### ISSUE THREAD

**Issue by opoplawski** [enthought/pyface#1248]
## Environment

OS: Linux - Fedora Rawhide
Python version: 3.11.3
Toolkit: Qt
Qt API: PyQt6 - 6.5.1

## Description

I'm working on updating the Fedora pyface package to 8.0.0 and hitting the following test failure:
```
test_basic (pyface.timer.tests.test_timer.TestTimer.test_basic) ... ok
test_repeat (pyface.timer.tests.test_timer.TestTimer.test_repeat) ... ok
test_restart (pyface.timer.tests.test_timer.TestTimer.test_restart) ... ok
test_different_lexer (pyface.ui.qt.code_editor.tests.test_code_widget.TestCodeWidget.test_different_lexer) ... ERROR
test_readonly_editor (pyface.ui.qt.code_editor.tests.test_code_widget.TestCodeWidget.test_readonly_editor) ... ERROR
test_readonly_replace_widget (pyface.ui.qt.code_editor.tests.test_code_widget.TestCodeWidget.test_readonly_replace_widget) ... ERROR
test_format_as_columns (pyface.ui.qt.console.tests.test_console_widget.TestConsoleWidget.test_format_as_columns) ... ERROR
test_right_key_press (pyface.ui.qt.console.tests.test_console_widget.TestConsoleWidget.test_right_key_press) ... ERROR
test_mimeData (pyface.ui.qt.data_view.tests.test_data_view_item_model.TestDataViewItemModel.test_mimeData) ... ok
test_mimeData_empty (pyface.ui.qt.data_view.tests.test_data_view_item_model.TestDataViewItemModel.test_mimeData_empty) ... ok
test_get_mimedata (pyface.ui.qt.data_view.tests.test_data_wrapper.TestDataWrapper.test_get_mimedata) ... ok
test_set_mimedata (pyface.ui.qt.data_view.tests.test_data_wrapper.TestDataWrapper.test_set_mimedata) ... ok
test_dock_windows_undock (pyface.ui.qt.tasks.tests.test_dock_pane.TestDockPane.test_dock_windows_undock) ... ERROR
test_dock_windows_visible_on_macos (pyface.ui.qt.tasks.tests.test_dock_pane.TestDockPane.test_dock_windows_visible_on_macos) ... skipped 'only applicable to macOS'
test_set_pane_item_height_in_main_window_layout (pyface.ui.qt.tasks.tests.test_main_window_layout.TestMainWindowLayout.test_set_pane_item_height_in_main_window_layout) ... FAIL
test_set_pane_item_width_in_main_window_layout (pyface.ui.qt.tasks.tests.test_main_window_layout.TestMainWindowLayout.test_set_pane_item_width_in_main_window_layout) ... ok
test_active_editor_after_focus_change (pyface.ui.qt.tasks.tests.test_split_editor_area_pane.TestEditorAreaWidget.test_active_editor_after_focus_change) ... ERROR
Traceback (most recent call last):
  File "/home/orion/BUILDROOT/python-pyface-8.0.0-1.fc39.x86_64/usr/lib/python3.11/site-packages/pyface/ui/qt/window.py", line 207, in eventFilter
    window = self._window()
             ^^^^^^^^^^^^
AttributeError: 'WindowEventFilter' object has no attribute '_window'
Traceback (most recent call last):
  File "/home/orion/BUILDROOT/python-pyface-8.0.0-1.fc39.x86_64/usr/lib/python3.11/site-packages/pyface/ui/qt/window.py", line 207, in eventFilter
    window = self._window()
             ^^^^^^^^^^^^
AttributeError: 'WindowEventFilter' object has no attribute '_window'
Fatal Python error: Aborted

Current thread 0x00007f626ab8e740 (most recent call first):
  Garbage-collecting
  File "/home/orion/BUILDROOT/python-pyface-8.0.0-1.fc39.x86_64/usr/lib/python3.11/site-packages/pyface/ui/qt/util/gui_test_assistant.py", line 77 in tearDown
  File "/usr/lib64/python3.11/unittest/case.py", line 584 in _callTearDown
  File "/usr/lib64/python3.11/unittest/case.py", line 626 in run
  File "/usr/lib64/python3.11/unittest/case.py", line 678 in __call__
  File "/usr/lib64/python3.11/unittest/suite.py", line 122 in run
  File "/usr/lib64/python3.11/unittest/suite.py", line 84 in __call__
  File "/usr/lib64/python3.11/unittest/suite.py", line 122 in run
  File "/usr/lib64/python3.11/unittest/suite.py", line 84 in __call__
  File "/usr/lib64/python3.11/unittest/suite.py", line 122 in run
  File "/usr/lib64/python3.11/unittest/suite.py", line 84 in __call__
  File "/usr/lib64/python3.11/unittest/suite.py", line 122 in run
  File "/usr/lib64/python3.11/unittest/suite.py", line 84 in __call__
  File "/usr/lib64/python3.11/unittest/runner.py", line 217 in run
  File "/usr/lib64/python3.11/unittest/main.py", line 274 in runTests
  File "/usr/lib64/python3.11/unittest/main.py", line 102 in __init__
  File "/usr/lib64/python3.11/unittest/__main__.py", line 18 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main

Extension modules: traits.ctraits, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, PyQt6.QtCore, PyQt6.QtGui, PyQt6.QtWidgets, PyQt6.QtPrintSupport, PyQt6.QtSvg, PyQt6.QtSvgWidgets, PIL._imaging, PyQt6.QtTest, wx._core, wx._grid, numpy.linalg.lapack_lite, systemd._journal, systemd._reader, systemd.id128, report._py3report, _dbus_bindings, problem._py3abrt (total: 31)
/usr/bin/xvfb-run: line 181: 47374 Aborted                 (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
error: Bad exit status from /var/tmp/rpm-tmp.O3KRhp (%check)
```

## Steps to Reproduce
```
+ export QT_API=pyqt6
+ export ETS_TOOLKIT=qt
+ export EXCLUDE_TESTS=wx
+ xvfb-run /usr/bin/python3 -Xfaulthandler -s -m unittest discover -v pyface
```

**Comment by corranwebster** [comment]
Thanks for the report - we've seen issues with PySide 6.5.1 in a number of other packages.  We may need to restrict to PySide <= 6.5.0 in the short term.
