### ISSUE TITLE
qApp returns "NoneType" object in PySide 1.0.3 

### ISSUE THREAD

**Issue by itziakos** [enthought/pyface#2]
Running the python_shell example in pyface under PySide (version 1.0.3) fails with the following error

---

python -u "python_shell.py"
Traceback (most recent call last):
  File "python_shell.py", line 51, in <module>
    window.open()
  File "/home/ioannis/projects/ets/pyface/pyface/i_window.py", line 145, in open
    self._create()
  File "/home/ioannis/projects/ets/pyface/pyface/ui/qt4/application_window.py", line 122, in _create
    contents = self._create_contents(self.control)
  File "python_shell.py", line 39, in _create_contents
    self._shell = PythonShell(parent)
  File "/home/ioannis/projects/ets/pyface/pyface/ui/qt4/python_shell.py", line 63, in __init__
    self.control = self._create_control(parent)
  File "/home/ioannis/projects/ets/pyface/pyface/ui/qt4/python_shell.py", line 86, in _create_control
    return PyfacePythonWidget(self, parent)qApp.
  File "/home/ioannis/projects/ets/pyface/pyface/ui/qt4/python_shell.py", line 493, in __init__
    super(PyfacePythonWidget, self).**init**(_args, *_kw)
  File "/home/ioannis/projects/ets/pyface/pyface/ui/qt4/python_shell.py", line 104, in **init**
    super(PythonWidget, self).**init**(parent)
  File "/home/ioannis/projects/ets/pyface/pyface/ui/qt4/console/history_console_widget.py", line 18, in **init**
    super(HistoryConsoleWidget, self).**init**(_args, *_kw)
  File "/home/ioannis/projects/ets/pyface/pyface/ui/qt4/console/console_widget.py", line 170, in **init**
    self.reset_font()
  File "/home/ioannis/projects/ets/pyface/pyface/ui/qt4/console/console_widget.py", line 771, in reset_font
    font.setPointSize(QtGui.qApp.font().pointSize())
AttributeError: 'NoneType' object has no attribute 'font'
## Exit code: 1

It seems that the qApp (used in pyface/ui/qt4/console/console_widget.py) is returning a "NoneType" object. This is corrected by replacing it with a call to QtGui.QApplication

Regards,
Ioannis

**Comment by corranwebster** [comment]
Resolved.
