### ISSUE TITLE
Missing RemoveEventHandler on ApplicationWindow.close on Mac OS

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#201]
OS: OS X 10.11.2
wxPython: 2.9.2.4-1 and 3.0.2.0
Pyface 5.0.0

```
from pyface.ui.wx.application_window import ApplicationWindow

win = ApplicationWindow()
win.open()
win.close()
```

gives
```
Traceback (most recent call last):
  File "failed.py", line 5, in <module>
    win.close()
  File "/Users/kit/ETS/jaguar/.jaguar/envs/test-mayavi/lib/python2.7/site-packages/pyface-5.0.0-py2.7.egg/pyface/ui/wx/application_window.py", line 198, in close
    super(ApplicationWindow, self).close()
  File "/Users/kit/ETS/jaguar/.jaguar/envs/test-mayavi/lib/python2.7/site-packages/pyface-5.0.0-py2.7.egg/pyface/i_window.py", line 181, in close
    self.destroy()
  File "/Users/kit/ETS/jaguar/.jaguar/envs/test-mayavi/lib/python2.7/site-packages/pyface-5.0.0-py2.7.egg/pyface/ui/wx/application_window.py", line 188, in destroy
    self._aui_manager.UnInit()
  File "/Users/kit/ETS/jaguar/.jaguar/envs/test-mayavi/lib/python2.7/site-packages/wx/aui.py", line 596, in UnInit
    return _aui.AuiManager_UnInit(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at /Users/vagrant/pisi-64bit/tmp/wxPython-3.0.2.0-2/work/wxPython-src-3.0.2.0/src/common/wincmn.cpp(1517) in RemoveEventHandler(): where has the event handler gone?
```

**Comment by kitchoi** [comment]
Fixed on master.  Sorry about that.
