### ISSUE TITLE
clipboard and pbpaste don't communicate on OSX

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#234]
Setting `clipboard.text_data` manually doesn't convey the copied data to `pbpaste` on OSX.

```
>>> from pyface.api import clipboard
>>> import pandas
>>> 
>>> clipboard.text_data = 'a,b,c\n1,2,3\n4,5,6'
>>> pandas.read_clipboard()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rahulporuri/Github/canopy-data-import/.devenv/lib/python2.7/site-packages/pandas/io/clipboard.py", line 51, in read_clipboard
    return read_table(StringIO(text), **kwargs)
  File "/Users/rahulporuri/Github/canopy-data-import/.devenv/lib/python2.7/site-packages/pandas/io/parsers.py", line 645, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/rahulporuri/Github/canopy-data-import/.devenv/lib/python2.7/site-packages/pandas/io/parsers.py", line 388, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/rahulporuri/Github/canopy-data-import/.devenv/lib/python2.7/site-packages/pandas/io/parsers.py", line 729, in __init__
    self._make_engine(self.engine)
  File "/Users/rahulporuri/Github/canopy-data-import/.devenv/lib/python2.7/site-packages/pandas/io/parsers.py", line 922, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/rahulporuri/Github/canopy-data-import/.devenv/lib/python2.7/site-packages/pandas/io/parsers.py", line 1389, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 538, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:5896)
pandas.io.common.EmptyDataError: No columns to parse from file
```

digging into the implementation, `pandas.read_clipboard` uses `pbcopy/pbpaste`.

```
>>> clipboard.text_data = 'a,b,c\n1,2,3\n4,5,6'
>>> subprocess.call('pbpaste')
0
```

**Comment by corranwebster** [comment]
Which backend?  The Qt backend is a fairly thin wrapper around the QClipboard class (with a custom mimetype for python objects, but that's not relevant here) and generally works with OS X copy/paste across apps, so the real question is what is needed to work with pbpaste (which I have no experience with).

**Comment by pankajp** [comment]
Qt backend. There also is some system specific issue, because thought I saw the issue on @rahulporuri 's machine, I could not reproduce it on two different systems, running MacOS Sierra and one something older.

**Comment by corranwebster** [comment]
Very quick look, problem is you don't want to use `subprocess.call` - it is behaving as expected (which is that `pbpaste` ran successfully and returned 0 to indicate that) but you haven't captured standard out which is where the clipboard text will have actually gone.  So you need to use `subprocess.check_output` or something similar.

Although when I try it I am getting some sort of lock-up if I try to do the subprocess `check_output` call in the same process as setting the data (the subprocess call hangs).

In any case, this looks like a Qt/subprocess issue rather than a pyface one.

**Comment by pankajp** [comment]
@corranwebster You might be correct, the lockup you are seeing is the issue under investigation.
Most OS's clipboards are programmatic, i.e. the application can keep the data and give it to the OS only when someone asks for it. For Qt, that mean having the event loop running when someone requests the clipboard data. That probably means the need to use the gui.proecss_events() or something like that when running the subprocess pbpaste.
Just a hypothesis, maybe someone can verify: @rahulporuri

**Comment by corranwebster** [comment]
@rahulporuri @pankajp is this resolved?

**Comment by pankajp** [comment]
Yes, this issue is resolved. Qt clipboard need the event loop to be running to be able to paste.
