### ISSUE TITLE
Broken enaml example

### ISSUE THREAD

**Issue by jonathanrocher** [enthought/pyface#34]
It seems like the example didnd't stay in sync with the current trunk of enaml...

Jonathan

```
jrocher:enaml jrocher$ ETS_TOOLKIT='qt4' python run.py 
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    main(sys.argv)
  File "run.py", line 18, in main
    window.add_task(task)
  File "/Users/jrocher/Projects/ETS_trunk/pyface/pyface/tasks/task_window.py", line 190, in add_task
    dock_pane.create(self.control)
  File "/Users/jrocher/Projects/ETS_trunk/pyface/pyface/ui/qt4/tasks/dock_pane.py", line 66, in create
    contents = self.create_contents(control)
  File "/Users/jrocher/Projects/ETS_trunk/pyface/pyface/tasks/enaml_dock_pane.py", line 26, in create_contents
    self.component = self.create_component()
  File "/Users/jrocher/Projects/ETS_trunk/pyface/examples/tasks/enaml/enaml_panes.py", line 19, in create_component
    from employee_view import EmployeeView
  File "/Users/jrocher/Projects/ETS_trunk/enaml/enaml/core/import_hooks.py", line 131, in load_module
    exec code in mod.__dict__
  File "/Users/jrocher/Projects/ETS_trunk/pyface/examples/tasks/enaml/employee_view.enaml", line 1, in 
    #------------------------------------------------------------------------------
  File "/Users/jrocher/Projects/ETS_trunk/pyface/examples/tasks/enaml/phone_converter.py", line 7, in <module>
    from enaml.converters import Converter
ImportError: No module named converters
```

**Comment by corranwebster** [comment]
Should have been fixed by #92
