### ISSUE TITLE
GuiTestAssistant requires TraitsUI

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#341]
[Motivated by [this comment](https://github.com/enthought/buildsystem/pull/1782#issuecomment-420044796)]

There's a hidden dependence of the `GuiTestAssistant` on Traits UI. I'm opening this issue as a placeholder; I intend to come back to this to fill out the details.

**Comment by mdickinson** [comment]
Okay, it's not so hidden; it's [here](https://github.com/enthought/pyface/blob/8b006017b429daf3d17974283eb722a9d8dabbdd/pyface/ui/qt4/util/gui_test_assistant.py#L40-L42)

```python
        self.traitsui_raise_patch = mock.patch(
            'traitsui.qt4.ui_base._StickyDialog.raise_')
        self.traitsui_raise_patch.start()
```

Here's a relevant traceback.
```
======================================================================
ERROR: test_synchronous_message_sending (traits_futures.qt.tests.test_message_router.TestMessageRouter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/.edm/envs/testing/lib/python2.7/site-packages/traits_futures/qt/tests/test_message_router.py", line 42, in setUp
    GuiTestAssistant.setUp(self)
  File "/Users/mdickinson/.edm/envs/testing/lib/python2.7/site-packages/pyface/ui/qt4/util/gui_test_assistant.py", line 42, in setUp
    self.traitsui_raise_patch.start()
  File "/Users/mdickinson/.edm/envs/testing/lib/python2.7/site-packages/mock/mock.py", line 1500, in start
    result = self.__enter__()
  File "/Users/mdickinson/.edm/envs/testing/lib/python2.7/site-packages/mock/mock.py", line 1353, in __enter__
    self.target = self.getter()
  File "/Users/mdickinson/.edm/envs/testing/lib/python2.7/site-packages/mock/mock.py", line 1523, in <lambda>
    getter = lambda: _importer(target)
  File "/Users/mdickinson/.edm/envs/testing/lib/python2.7/site-packages/mock/mock.py", line 1206, in _importer
    thing = __import__(import_path)
ImportError: No module named traitsui

```
