### ISSUE TITLE
test test_editor_area_pane.py hints wx pyface backend doesn't implement EditorAreaPane

### ISSUE THREAD

**Issue by idella** [enthought/pyface#40]
version:  4.1.0

 PYTHONPATH=build-2.7/lib nosetests --verbosity=1
Xlib:  extension "RANDR" missing on display ":10".
# ...EE..................

ERROR: Does creating an editor work?

---

Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/pyface-4.1.0/work/pyface-4.1.0/pyface/tasks/tests/test_editor_area_pane.py", line 13, in test_create_editor
    area = EditorAreaPane()
  File "/mnt/gen2/TmpDir/portage/dev-python/pyface-4.1.0/work/pyface-4.1.0/pyface/toolkit.py", line 92, in **init**
    raise NotImplementedError("the %s pyface backend doesn't implement %s" % (ETSConfig.toolkit, oname))
NotImplementedError: the wx pyface backend doesn't implement EditorAreaPane
# 

ERROR: Does registering and unregistering factories work?

---

Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/pyface-4.1.0/work/pyface-4.1.0/pyface/tasks/tests/test_editor_area_pane.py", line 20, in test_factories
    area = EditorAreaPane()
  File "/mnt/gen2/TmpDir/portage/dev-python/pyface-4.1.0/work/pyface-4.1.0/pyface/toolkit.py", line 92, in **init**
    raise NotImplementedError("the %s pyface backend doesn't implement %s" % (ETSConfig.toolkit, oname))
NotImplementedError: the wx pyface backend doesn't implement EditorAreaPane

---

Ran 23 tests in 1.044s

FAILED (errors=2)

Is it a problem with Xlib:  extension "RANDR" missing on display ":10".
or does the test prove the wx pyface backend doesn't implement EditorAreaPane?

**Comment by corranwebster** [comment]
Closing.  Appears resolved, plus Tasks now works with Wx and we're a lot better about guarding tests against the wrong toolkit.
