### ISSUE TITLE
Deprecation warnings under Python 3.6 + wxPython 4.0.1 backend running the demo example

### ISSUE THREAD

**Issue by mprogram** [enthought/pyface#416]
https://docs.enthought.com/mayavi/mayavi/mlab.html
```
$ env QT_API=pyside2 ETS_TOOLKIT=wx idle-python3.6
14:29:56: Debug: Adding duplicate image handler for 'Windows bitmap file'
14:29:56: Debug: Adding duplicate image handler for 'Windows bitmap file'
14:29:58: Debug: Unsupported OpenGL attribute 32
```
in IDLE:
```
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
======================= RESTART: ~/demo.py =======================

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/clipboard.py", line 25
    PythonObjectFormat = wx.CustomDataFormat('PythonObject')
wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/pyface/wx/drag_and_drop.py", line 99
    PythonObject = wx.CustomDataFormat('PythonObject')
wxPyDeprecationWarning: Call to deprecated item. Use wx.DataFormat instead.

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/action/action_item.py", line 378
    self.control_id, label, bmp, wx.NullBitmap, kind, tooltip, longtip, None
wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/action/action_item.py", line 396
    wx.EVT_TOOL(parent, self.control_id, self._on_tool)
wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/window.py", line 198
    self._position = event.GetEventObject().GetPositionTuple()
wxPyDeprecationWarning: Call to deprecated item. Use GetPosition instead
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/window.py", line 198, in _wx_on_control_move
    self._position = event.GetEventObject().GetPositionTuple()
  File "/usr/lib/python3/dist-packages/traits/trait_handlers.py", line 236, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The '_position' trait of a MayaviViewer instance must be a tuple of the form: (a value of class 'int', a value of class 'int'), but a value of wx.Point(900, 730) <class 'wx._core.Point'> was specified.

=============================== RESTART: Shell ===============================
>>> 
```

**Comment by mprogram** [comment]
Does the backend matter? I'm getting a **non-tiled** mesh under `ETS_TOOLKIT=qt`, whereas under `wx` it is both, meshed **and** tiled.

**Comment by mprogram** [comment]
I see the warnings are being related to #288, also #287 for a similar PR and some discussion.
