### ISSUE TITLE
AttributeError: module 'wx' has no attribute 'SplashScreen' in pyface/ui/wx/splash_screen.py", line 69 under Python3 / wxPython4

### ISSUE THREAD

**Issue by mprogram** [enthought/pyface#421]
see https://docs.enthought.com/mayavi/mayavi/mlab.html
`$ env QT_API=pyqt ETS_TOOLKIT=wx mayavi2 ~/demo.py `
``` python
16:56:22: Debug: Adding duplicate image handler for 'Windows bitmap file'
16:56:22: Debug: Adding duplicate image handler for 'Windows bitmap file'
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.plugins.mayavi_ui_plugin.MayaviUIPlugin object at 0x7f2a83736bf8>, trait: application, old value: None, new value: <mayavi.plugins.mayavi_workbench_application.MayaviWorkbenchApplication object at 0x7f2a83736eb8>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 654, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/usr/lib/python3/dist-packages/traits/traits_listener.py", line 498, in handle_simple
    self.next.register(new)
  File "/usr/lib/python3/dist-packages/traits/traits_listener.py", line 464, in register
    value = getattr(self, type)(new, name, False)
  File "/usr/lib/python3/dist-packages/traits/traits_listener.py", line 738, in _register_simple
    return next.register(getattr(object, name))
  File "/usr/lib/python3/dist-packages/envisage/ui/workbench/workbench_application.py", line 132, in _gui_default
    return GUI(splash_screen=self.splash_screen)
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/gui.py", line 60, in __init__
    self._splash_screen.open()
  File "/usr/lib/python3/dist-packages/pyface/i_splash_screen.py", line 79, in open
    super(MSplashScreen, self).open()
  File "/usr/lib/python3/dist-packages/pyface/i_window.py", line 202, in open
    self._create()
  File "/usr/lib/python3/dist-packages/pyface/i_widget.py", line 112, in _create
    self.control = self._create_control(self.parent)
  File "/usr/lib/python3/dist-packages/pyface/ui/wx/splash_screen.py", line 69, in _create_control
    splash_screen = wx.SplashScreen(
AttributeError: module 'wx' has no attribute 'SplashScreen'
(repeated)
```

**Comment by rahulporuri** [comment]
It looks like this got fixed in https://github.com/enthought/pyface/pull/469/. Closing.
