### ISSUE TITLE
etstool.py: not possible to use non-EDM Python as bootstrap environment

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#439]
It's convenient to be able to use a system-installed Python as the environment for running etstool.py. That works on macOS and Linux (provided that that system-installed Python has a few basic packages installed, like `click`), but not on Windows under either CMD or PowerShell:

```
PS C:\Users\Mark\Desktop\pyface> python etstool.py install
Creating environment 'pyface-test-3.6-pyqt'
[EXECUTING] edm environments create pyface-test-3.6-pyqt --force --version=3.6
Traceback (most recent call last):
  File "etstool.py", line 424, in <module>
    cli()
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "etstool.py", line 187, in install
    execute(commands, parameters)
  File "etstool.py", line 416, in execute
    arg.format(**parameters) for arg in command.split()
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by mdickinson** [comment]
The issue here is that, outside an EDM environment, the 'edm' command on Windows refers to a batch file, while inside an EDM environment, it refers to a genuine executable.

**Comment by corranwebster** [comment]
This is going to be an issue across all of the ETS projects, I guess?

**Comment by mdickinson** [comment]
Yes. It's more messy to fix that I'd like. A quick fix is to always use "edm.bat" instead of "edm" on Windows. That *mostly* works, except that "edm.bat" mangles some command-line arguments before they get passed to the actual executable, meaning that things like "pyqt<4.12" get misinterpreted. (I consider that a bug in EDM, but it's not one that's likely to be fixed any time soon.) So the ideal is to locate the actual edm executable (which won't usually be in the path) and use that.

**Comment by mdickinson** [comment]
And the quick cross-Python-version (but Windows-only) way to locate the "edm.bat" file is to use `subprocess.check_output(["where", "edm"])`. Having located the batch file, the executable should be next to it in "<path_to_batch_file>/embedded/edm.exe".

**Comment by mdickinson** [comment]
Assigning to me; I need to solve this for a number of different projects.
