### ISSUE TITLE
PyFace requires pygments, but pygments is not listed in the dependencies.

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#446]
The most recent release of PyFace (6.1.2) appears to require `pygments`: a simple `import pyface.api` will fail if `pygments` is not installed.

We should either fix so that `import pyface.api` succeeds if `pygments` is not installed, or add `pygments` to the dependencies.

**Comment by mdickinson** [comment]
Here's the traceback, and the contents of my Python 3.7 VM after installing Pyface from PyPI:
```
(entest) mirzakhani:Desktop mdickinson$ pip freeze
apptools==4.4.0
configobj==5.0.6
envisage==4.8.0
nose==1.3.7
pyface==6.1.2
PyQt5==5.13.0
PyQt5-sip==4.19.18
six==1.12.0
traits==5.1.2
traitsui==6.1.3
(entest) mirzakhani:Desktop mdickinson$ python
Python 3.7.4 (default, Jul 11 2019, 01:08:00) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyface.api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/api.py", line 36, in <module>
    from .python_editor import PythonEditor
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/python_editor.py", line 21, in <module>
    PythonEditor = toolkit_object('python_editor:PythonEditor')
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/base_toolkit.py", line 144, in __call__
    module = import_module(mname, package)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/ui/qt4/python_editor.py", line 27, in <module>
    from pyface.ui.qt4.code_editor.code_widget import AdvancedCodeWidget
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/ui/qt4/code_editor/code_widget.py", line 23, in <module>
    from .pygments_highlighter import PygmentsHighlighter
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/ui/qt4/code_editor/pygments_highlighter.py", line 14, in <module>
    from pygments.lexer import RegexLexer, _TokenType, Text, Error
ModuleNotFoundError: No module named 'pygments'
```

**Comment by mdickinson** [comment]
It looks as though `pygments` *is* in the EDM requirements, but not in the `setup.py` requirements.

**Comment by corranwebster** [comment]
`pygments` is an _optional_ dependency (it isn't needed for the Wx backend) and is listed as such: https://github.com/enthought/pyface/blob/master/pyface/__init__.py#L27

**Comment by mdickinson** [comment]
Sorry; looking at the code, I now understand. `pygments` is only required for the Qt backends.

It's unfortunate that this means that `pip install pyface pyqt5` gives a non-functional Pyface, though. I wonder if there's any reasonable way to fix that.

**Comment by mdickinson** [comment]
Is there a way that we could push the `pygments` imports down so that they're not encountered immediately on `import pyface.api`?

**Comment by corranwebster** [comment]
So the "correct" way to pip install with the pyqt5 backend would be `pip install pyface[pyqt5]` - but it looks like it is currently not working for some reason (can't find a matching pyqt version).
