### ISSUE TITLE
Unable to import pyface.ui.wx.grid.api

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#528]
Motivated by this issue from TraitsUI
https://github.com/enthought/traitsui/issues/863

Attempt to import `pyface.ui.wx.grid.api` leads to the following errors:
```
>>> import pyface.ui.wx.grid.api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/ui/wx/grid/api.py", line 21, in <module>
    from .trait_grid_model import TraitGridModel, TraitGridColumn, \
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/ui/wx/grid/trait_grid_model.py", line 28, in <module>
    from .trait_grid_cell_adapter import TraitGridCellAdapter
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/ui/wx/grid/trait_grid_cell_adapter.py", line 22, in <module>
    from combobox_focus_handler import ComboboxFocusHandler
ModuleNotFoundError: No module named 'combobox_focus_handler'
```

**Comment by kitchoi** [comment]
I was trying to diagnose and then immediately realized that I was actually using an out-of-date version of pyface in my development environment.
Closing. Sorry for the noise.
