### ISSUE TITLE
'QKeyEvent' object has no attribute 'size'

### ISSUE THREAD

**Issue by notmatthancock** [enthought/pyface#550]
Since upgrading our application to pyqt5, I get this traceback every time the window is resized:

```
Traceback (most recent call last):
  File ".../pyface/ui/qt4/window.py", line 233, in eventFilter
    size = e.size()
AttributeError: 'QKeyEvent' object has no attribute 'size'
```

**Comment by corranwebster** [comment]
Dumb question first: how are you resizing?  Dragging with a mouse, using a keyboard command, double-clicking a title-bar? clicking a window enlarge button?  Do you see different behaviour under different circumstances?  It's probably also useful to know the OS you're running on when you see this, and if you see the same behaviour

This feels like it might be a bug in PyQt/Qt, as the only way to get to that branch is if `e.type() == QtCore.QEvent.Resize` and from the Qt docs:

> The type parameter must be QEvent::KeyPress, QEvent::KeyRelease, or QEvent::ShortcutOverride.

So on the face of it, this is impossible.  Clearly it's happening, but a QKeyEvent should never be able to get to that point in the code.

Th other possibility is something mutating the event, but I don't see any Pyface code that changes with the event type, and in that case we should see it on other PyQt versions.

**Comment by notmatthancock** [comment]
> It's probably also useful to know the OS you're running on when you see this, and if you see the same behaviour

Ubuntu.

> how are you resizing? 

Shown here mouse-dragging, but double clicking the title bar has the same effect:

![qkey](https://user-images.githubusercontent.com/1588456/85718359-0d327300-b6b4-11ea-8573-c394c9c3a96b.gif)

**Comment by notmatthancock** [comment]
Aha -- I just discovered that I only observe these errors if the visibility of a dockpane was previously toggled via a keyboard shortcut :thinking:

**Comment by corranwebster** [comment]
Any threading going on?

**Comment by notmatthancock** [comment]
> Any threading going on?

No.

**Comment by rkern** [comment]
I used to see this kind of "impossible" type corruption on event objects when using PySide. Never could pin down exactly what was going wrong. I assumed that it was a bug in the wrapper code that creates the Python object from the Qt object.

**Comment by notmatthancock** [comment]
I am able to reproduce the issue using the following steps and code snippet:

1. Run the code below
2. Click on the window and press keys on the keyboard (this is important; otherwise, the crash does not occur)
3. Resize the window and receive traceback:
```
Traceback (most recent call last):
  File "...pyface/ui/qt4/window.py", line 233, in eventFilter
    size = e.size()
AttributeError: 'QKeyEvent' object has no attribute 'size'
Aborted (core dumped)
```

```python
from pyface.api import ApplicationWindow, GUIApplication


class TestWindow(ApplicationWindow):
    title = "Hi everybody"

    def _create_contents(self, parent):
        """ Create the shell widget. """
        from PyQt5.QtWidgets import QLabel
        return QLabel('Hello everybody')


if __name__ == '__main__':
    app = GUIApplication(window_factory=TestWindow)
    app.run()
```

**Comment by notmatthancock** [comment]
This error does not appear to occur on Windows. I have not tested on Mac OS.

**Comment by jvkersch** [comment]
I've encountered exactly the same error (on Linux) under the same circumstances (triggering a key event first and then resizing the window). Like @rkern I've had trouble digging in further: I tried setting a breakpoint in the event handler to take a closer look, but that makes the problem go away.

**Comment by notmatthancock** [comment]
I checked with a couple of MacOS users on my team, and they have not observed this issue. So it would appear that this is only a Linux problem.
