### ISSUE TITLE
Test failures with PyQt5 5.15.0 from PyPI

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#581]
This is probably not something we can fix but still something we can probably pin to the repository to notify users. As far as I know, this is an issue with the PyQt5 PyPI wheel.

```
======================================================================
ERROR: test_imports (pyface.ui.qt4.tests.test_qt_imports.TestPyfaceQtImports)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\rporuri\work\github\ets\pyface\pyface\qt\QtWebKit.py", line 19, in <module>
    from PyQt5.QtWebEngine import *
ModuleNotFoundError: No module named 'PyQt5.QtWebEngine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rporuri\work\github\ets\pyface\pyface\ui\qt4\tests\test_qt_imports.py", line 24, in test_imports
    import pyface.qt.QtWebKit
  File "C:\Users\rporuri\work\github\ets\pyface\pyface\qt\QtWebKit.py", line 28, in <module>
    from PyQt5.QtWebKit import *
ModuleNotFoundError: No module named 'PyQt5.QtWebKit'
----------------------------------------------------------------------
```

**Comment by kitchoi** [comment]
Related to #418

**Comment by rahulporuri** [comment]
@kitchoi is this still in progress? If not, i'll move this from In progress Q4 2020 to TBC Q1 2021.

**Comment by kitchoi** [comment]
@rahulporuri Yes it is for #853 is being reviewed.
