### ISSUE TITLE
Test failures due to requirement on numpy

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#742]
NumPy is not an install requirement for Pyface + Qt.
But running the test suite in an environment created with `pip install <source-distribution-file>[pyside2,test]` results in the following errors:
```
======================================================================
ERROR: pyface.data_view.data_models.tests.test_array_data_model (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyface.data_view.data_models.tests.test_array_data_model
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/traits/trait_numeric.py", line 63, in __init__
    import numpy
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/data_view/data_models/tests/test_array_data_model.py", line 21, in <module>
    from pyface.data_view.data_models.array_data_model import ArrayDataModel
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/data_view/data_models/array_data_model.py", line 41, in <module>
    class ArrayDataModel(AbstractDataModel, HasRequiredTraits):
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/data_view/data_models/array_data_model.py", line 60, in ArrayDataModel
    data = _AtLeastTwoDArray()
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/traits/trait_numeric.py", line 318, in __init__
    super(Array, self).__init__(
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/traits/trait_numeric.py", line 65, in __init__
    raise TraitError(
traits.trait_errors.TraitError: Using Array or CArray trait types requires the numpy package to be installed.


======================================================================
ERROR: pyface.data_view.tests.test_data_view_widget (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyface.data_view.tests.test_data_view_widget
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/traits/trait_numeric.py", line 63, in __init__
    import numpy
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/data_view/tests/test_data_view_widget.py", line 22, in <module>
    from pyface.data_view.data_models.api import ArrayDataModel
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/data_view/data_models/api.py", line 11, in <module>
    from .array_data_model import ArrayDataModel  # noqa: F401
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/data_view/data_models/array_data_model.py", line 41, in <module>
    class ArrayDataModel(AbstractDataModel, HasRequiredTraits):
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/data_view/data_models/array_data_model.py", line 60, in ArrayDataModel
    data = _AtLeastTwoDArray()
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/traits/trait_numeric.py", line 318, in __init__
    super(Array, self).__init__(
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/traits/trait_numeric.py", line 65, in __init__
    raise TraitError(
traits.trait_errors.TraitError: Using Array or CArray trait types requires the numpy package to be installed.


======================================================================
ERROR: pyface.ui.qt4.data_view.tests.test_data_view_item_model (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyface.ui.qt4.data_view.tests.test_data_view_item_model
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/traits/trait_numeric.py", line 63, in __init__
    import numpy
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/ui/qt4/data_view/tests/test_data_view_item_model.py", line 16, in <module>
    from pyface.data_view.data_models.api import ArrayDataModel
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/data_view/data_models/api.py", line 11, in <module>
    from .array_data_model import ArrayDataModel  # noqa: F401
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/data_view/data_models/array_data_model.py", line 41, in <module>
    class ArrayDataModel(AbstractDataModel, HasRequiredTraits):
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/pyface/data_view/data_models/array_data_model.py", line 60, in ArrayDataModel
    data = _AtLeastTwoDArray()
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/traits/trait_numeric.py", line 318, in __init__
    super(Array, self).__init__(
  File "/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/traits/trait_numeric.py", line 65, in __init__
    raise TraitError(
traits.trait_errors.TraitError: Using Array or CArray trait types requires the numpy package to be installed.
```

I believe these tests should be skipped if numpy is not available.

**Comment by kitchoi** [comment]
Note that wx already depends on NumPy so these errors are not expected in an environment for Wx.

**Comment by aaronayres35** [comment]
The problematic line is: https://github.com/enthought/pyface/blob/dbe6f9aef89f40ad5b8185cac78a8eed5b05ee8d/pyface/ui/qt4/data_view/tests/test_data_view_item_model.py#L16
as `ArrayDataModel` uses `_AtLeastTwoDArray()` which subclasses `Array` from traits which tries to import numpy in its `__init__`

**Comment by aaronayres35** [comment]
> which subclasses `Array` from traits which tries to import numpy in its `__init__`

See: https://github.com/enthought/traits/blob/ef732cacbddbfa7bf3e994b49171780d10d445c3/traits/trait_numeric.py#L47-L70

**Comment by aaronayres35** [comment]
This attempt to solve the issue by moving the problem import into the TestCase class which was decorated with `@requires_numpy` failed to solve the problem:

```
@requires_numpy
class TestDataViewItemModel(TestCase):
    # This import results in an error without numpy installed
    # see enthought/pyface#742
    from pyface.data_view.data_models.api import ArrayDataModel
...
```
