### ISSUE TITLE
Traitsui integrationtests fail when used with pyface from master branch.

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#830]
The following two test failures occur when the traitsui testsuite is run using pyface from source (discovered in PR https://github.com/enthought/traitsui/pull/1427).

<details>

```
======================================================================
FAIL: test_run (test_all_examples.TestExample) (file_path='C:\\Users\\rporuri\\.edm\\envs\\traitsui-test-3.6-pyqt5\\lib\\site-packages\\traitsui\\examples\\demo\\Applications\\Python_source_browser.py')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\rporuri\work\github\ets\traitsui\integrationtests\test_all_examples.py", line 332, in test_run
    run_file(file_path)
TypeError: '__main__' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rporuri\work\github\ets\traitsui\integrationtests\test_all_examples.py", line 339, in test_run
    file_path, exc, message
AssertionError: Executing C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\examples\demo\Applications\Python_source_browser.py failed with exception '__main__' is not a package
 Traceback (most recent call last):
  File "C:\Users\rporuri\work\github\ets\traitsui\integrationtests\test_all_examples.py", line 332, in test_run
    run_file(file_path)
  File "C:\Users\rporuri\work\github\ets\traitsui\integrationtests\test_all_examples.py", line 273, in run_file
    exec(content, globals)
  File "<string>", line 176, in <module>
  File "C:\Users\rporuri\work\github\ets\traitsui\integrationtests\test_all_examples.py", line 232, in replaced_configure_traits
    with UITester().create_ui(instance, ui_kwargs):
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\testing\tester\ui_tester.py", line 88, in create_ui
    ui = object.edit_traits(**ui_kwargs)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\has_traits.py", line 1744, in edit_traits
    args,
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\view.py", line 462, in ui
    ui.ui(parent, kind)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\toolkit.py", line 163, in ui_live
    ui_live.ui_live(ui, parent)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_live.py", line 43, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_live.py", line 65, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_base.py", line 286, in display_ui
    ui.owner.init(ui, parent, style)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_live.py", line 225, in init
    self.add_contents(panel(ui), bbox)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 259, in panel
    panel = _GroupPanel(content[0], ui).control
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 555, in __init__
    self._add_splitter_items(content, splitter)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 648, in _add_splitter_items
    panel = _GroupPanel(item, self.ui, suppress_label=True).control
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 555, in __init__
    self._add_splitter_items(content, splitter)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 650, in _add_splitter_items
    panel = self._add_items([item])
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 891, in _add_items
    editor.prepare(inner)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\editor.py", line 236, in prepare
    self.init(parent)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\tabular_editor.py", line 240, in init
    self._add_image(image_resource)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\tabular_editor.py", line 351, in _add_image
    image = image_resource.create_icon()
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\pyface\ui\qt4\image_resource.py", line 55, in create_icon
    ref = self._get_ref(size)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\pyface\i_image_resource.py", line 194, in _get_ref
    self.name, self.search_path, size
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\pyface\resource\resource_manager.py", line 67, in locate_image
    return self._locate_image(image_name, resource_path, size)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\pyface\resource\resource_manager.py", line 123, in _locate_image
    files(dirname.__name__)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\importlib_resources\_common.py", line 24, in files
    return from_package(get_package(package))
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\importlib_resources\_common.py", line 73, in get_package
    raise TypeError('{!r} is not a package'.format(package))
TypeError: '__main__' is not a package


======================================================================
FAIL: test_run (test_all_examples.TestExample) (file_path='C:\\Users\\rporuri\\.edm\\envs\\traitsui-test-3.6-pyqt5\\lib\\site-packages\\traitsui\\examples\\demo\\Extras\\Image_editor_demo.py')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\rporuri\work\github\ets\traitsui\integrationtests\test_all_examples.py", line 332, in test_run
    run_file(file_path)
TypeError: '__main__' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rporuri\work\github\ets\traitsui\integrationtests\test_all_examples.py", line 339, in test_run
    file_path, exc, message
AssertionError: Executing C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\examples\demo\Extras\Image_editor_demo.py failed with exception '__main__' is not a package
 Traceback (most recent call last):
  File "C:\Users\rporuri\work\github\ets\traitsui\integrationtests\test_all_examples.py", line 332, in test_run
    run_file(file_path)
  File "C:\Users\rporuri\work\github\ets\traitsui\integrationtests\test_all_examples.py", line 273, in run_file
    exec(content, globals)
  File "<string>", line 77, in <module>
  File "C:\Users\rporuri\work\github\ets\traitsui\integrationtests\test_all_examples.py", line 232, in replaced_configure_traits
    with UITester().create_ui(instance, ui_kwargs):
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\testing\tester\ui_tester.py", line 88, in create_ui
    ui = object.edit_traits(**ui_kwargs)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\has_traits.py", line 1744, in edit_traits
    args,
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\view.py", line 462, in ui
    ui.ui(parent, kind)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\toolkit.py", line 163, in ui_live
    ui_live.ui_live(ui, parent)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_live.py", line 43, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_live.py", line 65, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_base.py", line 286, in display_ui
    ui.owner.init(ui, parent, style)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_live.py", line 225, in init
    self.add_contents(panel(ui), bbox)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 259, in panel
    panel = _GroupPanel(content[0], ui).control
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 615, in __init__
    layout = self._add_groups(content, inner)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 696, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 617, in __init__
    layout = self._add_items(content, inner)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 891, in _add_items
    editor.prepare(inner)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\editor.py", line 236, in prepare
    self.init(parent)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\image_editor.py", line 278, in init
    self.control.setPixmap(convert_bitmap(image))
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\pyface\ui_traits.py", line 85, in convert_bitmap
    ] = bitmap = image_resource.create_bitmap()
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\pyface\i_image_resource.py", line 164, in create_image
    ref = self._get_ref(size)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\pyface\i_image_resource.py", line 194, in _get_ref
    self.name, self.search_path, size
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\pyface\resource\resource_manager.py", line 67, in locate_image
    return self._locate_image(image_name, resource_path, size)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\pyface\resource\resource_manager.py", line 123, in _locate_image
    files(dirname.__name__)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\importlib_resources\_common.py", line 24, in files
    return from_package(get_package(package))
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\importlib_resources\_common.py", line 73, in get_package
    raise TypeError('{!r} is not a package'.format(package))
TypeError: '__main__' is not a package

```

</details>

This seems to be related to the recent change from `pkg_resources` to `importlib_metadata` in #790 .

**Comment by rahulporuri** [comment]
@aaronayres35 this is a release blocker for pyface 7.2.0. Can you investigate and fix this before continuing with the release?

**Comment by aaronayres35** [comment]
Looking into this, I think this is a problem (not sure why it wasn't causing issues before):

https://github.com/enthought/traitsui/blob/a2ad46405b5d876ff098bcc978371ab5e8855e8d/traitsui/examples/demo/Extras/Image_editor_demo.py#L30-L31

this effectively refers to a `examples/demo/Extras` folder in _traits_, but that doesn't exist.  In traitsui it does, and there is a subfolder called images which contains `e-logo-rev.png` and `info.png` which is seems we want to access here:
https://github.com/enthought/traitsui/blob/a2ad46405b5d876ff098bcc978371ab5e8855e8d/traitsui/examples/demo/Extras/Image_editor_demo.py#L50-L51
https://github.com/enthought/traitsui/blob/a2ad46405b5d876ff098bcc978371ab5e8855e8d/traitsui/examples/demo/Extras/Image_editor_demo.py#L72-L73

**Comment by aaronayres35** [comment]
I am no longer seeing the `Image_editor_demo.py` issue after changing the code here:
https://github.com/enthought/traitsui/blob/a2ad46405b5d876ff098bcc978371ab5e8855e8d/traitsui/examples/demo/Extras/Image_editor_demo.py#L50-L51
to this:
```
import traitsui.api
search_path = [join(dirname(traitsui.api.__file__),
                    '..', 'examples', 'demo', 'Extras')]
```

**Comment by aaronayres35** [comment]
Currently from the traitsui root directory I run:
```
python etstool.py install --toolkit=pyqt5 --source
edm shell -e traitsui-test-3.6-pyqt5
cd integrationtests
python -m unittest
```
and I see the two failures described in this issue.

Then I run:
```
cd ..
pip install -e .
cd integration tests
python -m unittest
```
And neither of the tests fail anymore.  I have made the change as described in the previous comment https://github.com/enthought/pyface/issues/830#issuecomment-738972393, and have some random print statements scattered about.  I have made no changes specific to the issue reported about `Python_source_browser.py`, but it somehow is no longer occurring for me locally... 

I then ran a git clean (and git pull as a sanity check but I was already up to date) and re-did the full process.  I again saw both errors initially, but after running `pip install -e .` I only see 1 error - I no longer see the `Python_source_browser.py` error.  I'm a bit confused on why this is happening? 

In any case with the fix I described I am no longer seeing any errors locally.

**Comment by aaronayres35** [comment]
> I then ran a git clean (and git pull as a sanity check but I was already up to date) and re-did the full process. I again saw both errors initially, but after running `pip install -e .` I only see 1 error - I no longer see the `Python_source_browser.py` error. I'm a bit confused on why this is happening?

FWIW this is the output of `pip install -e .`:
```
Obtaining file:///Users/aayres/Desktop/traitsui
Requirement already satisfied: traits>=6.0.0 in /Users/aayres/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages (from traitsui==7.2.0.dev416) (6.2.0.dev1651)
Requirement already satisfied: pyface>=7.1.0 in /Users/aayres/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages (from traitsui==7.2.0.dev416) (7.3.0.dev181)
Requirement already satisfied: importlib-metadata in /Users/aayres/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages (from pyface>=7.1.0->traitsui==7.2.0.dev416) (3.1.1)
Requirement already satisfied: importlib-resources>=1.1.0 in /Users/aayres/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages (from pyface>=7.1.0->traitsui==7.2.0.dev416) (3.3.0)
Requirement already satisfied: zipp>=0.5 in /Users/aayres/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages (from importlib-metadata->pyface>=7.1.0->traitsui==7.2.0.dev416) (3.4.0)
Installing collected packages: traitsui
  Attempting uninstall: traitsui
    Found existing installation: traitsui 7.2.0.dev416
    Uninstalling traitsui-7.2.0.dev416:
      Successfully uninstalled traitsui-7.2.0.dev416
  Running setup.py develop for traitsui
Successfully installed traitsui
```
and before and after calls to `pip list` all that changes is version / location goes from 
`7.2.0.dev416` -> `7.2.0.dev416  /Users/aayres/Desktop/traitsui`
but I have no local changes

**Comment by kitchoi** [comment]
There is definitely a regression here.

Following this step:
```
python3.9 -m venv py39-venv/traitsui-env
source py39-venv/traitsui-env/bin/activate
pip install pyface[pyside2]==7.2.0rc1
pip install traitsui
# copy the example to a test directory, the reference to the image is lost, but the application should not fail.
cp ~/Work/ETS/traitsui/examples/demo/Extras/Image_editor_demo.py .
python Image_editor_demo.py
```
and I get the error mentioned above:
```
... 
  File "/Users/kchoi/Work/ETS/py39-venv/traitsui-env/lib/python3.9/site-packages/traitsui/editor.py", line 236, in prepare
    self.init(parent)
  File "/Users/kchoi/Work/ETS/py39-venv/traitsui-env/lib/python3.9/site-packages/traitsui/qt4/image_editor.py", line 278, in init
    self.control.setPixmap(convert_bitmap(image))
  File "/Users/kchoi/Work/ETS/py39-venv/traitsui-env/lib/python3.9/site-packages/pyface/ui_traits.py", line 85, in convert_bitmap
    ] = bitmap = image_resource.create_bitmap()
  File "/Users/kchoi/Work/ETS/py39-venv/traitsui-env/lib/python3.9/site-packages/pyface/i_image_resource.py", line 164, in create_image
    ref = self._get_ref(size)
  File "/Users/kchoi/Work/ETS/py39-venv/traitsui-env/lib/python3.9/site-packages/pyface/i_image_resource.py", line 193, in _get_ref
    self._ref = resource_manager.locate_image(
  File "/Users/kchoi/Work/ETS/py39-venv/traitsui-env/lib/python3.9/site-packages/pyface/resource/resource_manager.py", line 67, in locate_image
    return self._locate_image(image_name, resource_path, size)
  File "/Users/kchoi/Work/ETS/py39-venv/traitsui-env/lib/python3.9/site-packages/pyface/resource/resource_manager.py", line 123, in _locate_image
    files(dirname.__name__)
  File "/Users/kchoi/Work/ETS/py39-venv/traitsui-env/lib/python3.9/site-packages/importlib_resources/_common.py", line 24, in files
    return from_package(get_package(package))
  File "/Users/kchoi/Work/ETS/py39-venv/traitsui-env/lib/python3.9/site-packages/importlib_resources/_common.py", line 73, in get_package
    raise TypeError('{!r} is not a package'.format(package))
TypeError: '__main__' is not a package
```
Then if I install pyface 7.1.0:
```
pip install pyface==7.1.0
```
and run the example again, I don't get the error, the application launches, with indications that there are missing images:
![Screenshot 2020-12-07 at 10 51 30](https://user-images.githubusercontent.com/3673984/101342233-2ef66f80-387a-11eb-8918-9f9464c3ec7e.png)
