### ISSUE TITLE
ETS_DEBUG errors when trying to debug import errrors

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#858]
When running code that generates an import error in the toolkit (which is almost guaranteed to happen, since not every toolkit supports every widget), I get:
```
Traceback (most recent call last):
  File "python_editor.py", line 14, in <module>
    from pyface.api import ApplicationWindow, FileDialog, GUI, OK, PythonEditor
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/pyface/api.py", line 66, in <module>
    from .expandable_panel import ExpandablePanel
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/pyface/expandable_panel.py", line 18, in <module>
    ExpandablePanel = toolkit_object("expandable_panel:ExpandablePanel")
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/pyface/base_toolkit.py", line 170, in __call__
    frames = traceback.extract_tb(sys.exc_traceback)
AttributeError: module 'sys' has no attribute 'exc_traceback'
```

The issue appears to be in this code:
https://github.com/enthought/pyface/blob/f2b2639187688659d291117e1733cc428d0dcfa6/pyface/base_toolkit.py#L164-L173

**Comment by rahulporuri** [comment]
closing as this got fixed in https://github.com/enthought/pyface/pull/936/
