### ISSUE TITLE
Traits observe handler error when running the testsuite

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#906]
I see the following traceback when I run the testsuite with python3.6 and pyqt5 against the latest changes on the main branch.

```
test_lifecycle (pyface.tasks.tests.test_tasks_application.TestApplication) ... Exception occurred in traits notification handler for event object: TraitChangeEvent(object=<pyface.ui.qt4.application_window.ApplicationWindow object at 0x000001BCBCA92678>, name='activated', old=<undefined>, new=<pyface.ui.qt4.application_window.ApplicationWindow object at 0x000001BCBCA92678>)
Traceback (most recent call last):
  File "C:\Users\rporuri\.edm\envs\pyface-test-3.6-pyqt5\lib\site-packages\traits\observation\_trait_event_notifier.py", line 122, in __call__
    self.dispatcher(handler, event)
  File "C:\Users\rporuri\.edm\envs\pyface-test-3.6-pyqt5\lib\site-packages\traits\observation\observe.py", line 26, in dispatch_same
    handler(event)
  File "C:\Users\rporuri\.edm\envs\pyface-test-3.6-pyqt5\lib\site-packages\pyface\gui_application.py", line 289, in _on_activate_window
    self.active_window = window
  File "C:\Users\rporuri\.edm\envs\pyface-test-3.6-pyqt5\lib\site-packages\traits\observation\_observer_change_notifier.py", line 152, in __call__
    dispatcher=self.dispatcher,
  File "C:\Users\rporuri\.edm\envs\pyface-test-3.6-pyqt5\lib\site-packages\traits\observation\_has_traits_helpers.py", line 114, in observer_change_handler
    remove=False,
  File "C:\Users\rporuri\.edm\envs\pyface-test-3.6-pyqt5\lib\site-packages\traits\observation\_observe.py", line 54, in add_or_remove_notifiers
    callable_()
  File "C:\Users\rporuri\.edm\envs\pyface-test-3.6-pyqt5\lib\site-packages\traits\observation\_observe.py", line 94, in __call__
    step()
  File "C:\Users\rporuri\.edm\envs\pyface-test-3.6-pyqt5\lib\site-packages\traits\observation\_observe.py", line 163, in _add_or_remove_notifiers
    for observable in self.graph.node.iter_observables(self.object):
  File "C:\Users\rporuri\.edm\envs\pyface-test-3.6-pyqt5\lib\site-packages\traits\observation\_named_trait_observer.py", line 88, in iter_observables
    "Trait named {!r} not found on {!r}.".format(self.name, object)
ValueError: Trait named 'active_task' not found on <pyface.ui.qt4.application_window.ApplicationWindow object at 0x000001BCBCA92678>.
ok
```

**Comment by aaronayres35** [comment]
Similar to your comment here: https://github.com/enthought/traitsui/pull/1545#pullrequestreview-617285587

I am not seeing this traceback when I run the test suite with pyqt5 and python 3.6 locally... strange
